services:
  db:
    image: postgres:latest
    container_name: "library_db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "LibraryDB"
    restart: always
    extra_hosts:
      - "database:172.17.0.1"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru" ]
    hostname: redis
    volumes:
      - redis-data:/data
volumes:
  db_data:
  redis-data:
