
name: Docker Compose Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      # Step 3: Make the HTTP GET request
      - name: Make HTTP GET request
        run: |
          curl -X GET http://localhost:5253/api/Departments
